# Generated by Django 3.0.2 on 2020-01-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdn_bpsdata',
            name='TimeStamp',
            field=models.DateTimeField(max_length=100, verbose_name='utc当前时间'),
        ),
        migrations.AlterField(
            model_name='cdn_bpsdata',
            name='end_time',
            field=models.DateTimeField(verbose_name='utc结束时间'),
        ),
        migrations.AlterField(
            model_name='cdn_bpsdata',
            name='start_time',
            field=models.DateTimeField(verbose_name='utc开始时间'),
        ),
        migrations.AlterField(
            model_name='cdn_trafficdata',
            name='TimeStamp',
            field=models.DateTimeField(max_length=100, verbose_name='utc当前时间'),
        ),
        migrations.AlterField(
            model_name='cdn_trafficdata',
            name='end_time',
            field=models.DateTimeField(max_length=100, verbose_name='utc结束时间'),
        ),
        migrations.AlterField(
            model_name='cdn_trafficdata',
            name='start_time',
            field=models.DateTimeField(max_length=100, verbose_name='utc开始时间'),
        ),
    ]
