# Generated by Django 3.0.2 on 2020-03-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsdata', '0002_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controls_info',
            fields=[
                ('timec_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='时间戳id')),
                ('DomainName', models.CharField(max_length=100, verbose_name='域名')),
                ('control_value', models.CharField(max_length=100, verbose_name='监控值')),
                ('control_count', models.CharField(max_length=100, verbose_name='连续次数')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.DeleteModel(
            name='Control',
        ),
    ]
